### ISSUE TITLE
Inconsistency version in badge and documentation and pip

### ISSUE THREAD

**Issue by BramVanroy** [cgnorthcutt/hypopt#12]
Just a small issue:

I see that the latest release on PyPi is 1.0.9. However, the badge on the readme states 1.0.2. On top of that, in one of the latest commits you describe it as an update to *0*.0.9. This might be a bit confusing.

Greetings

**Comment by cgnorthcutt** [comment]
I amended a followup commit to say 1.0.9 instead of 0.0.9. The badge on the readme is fixed now thanks!
