### ISSUE TITLE
Seeing very slow relative performance for a single training job/single core

### ISSUE THREAD

**Issue by mtpadilla** [cgnorthcutt/hypopt#2]
First off, thank you very much for making this tool public. It fits my needs in theory so I've been experimenting a bit to see if I can use it.

I tried your minimal example on my macbook pro (late 2018, 8 cores) and added a bit of code to check the running time of the default and "optimized" versions. I ran this with only single hyperparameter value, and set num_threads = 1. If I understand your code correctly, it seems that the running times should be identical. However, in your sample problem I'm seeing that on my machine it takes the default scheme ~0.01 sec while the optimized scheme is taking ~0.12 sec.

I'm attaching the simple notebook I used in this experiment. There's some irrelevant code that I tried out but have commented out. It's the same as your example except that param_grid has only one case.

Am I using your library incorrectly? Thank you.

[hypopt_minworkex.pdf](https://github.com/cgnorthcutt/hypopt/files/2255135/hypopt_minworkex.pdf)

**Comment by cgnorthcutt** [comment]
@mtpadilla - appreciate this comment, thanks! I agree and at the same time, no change is needed - this is correct behavior.

In short, no one should ever use a hyper-parameter optimization package on a set of parameters of size 1. Its non-sensical. If you are only choosing among a single setting of parameters, then just fit your model with those parameters. This package is for choosing THE BEST choice of parameters among a bunch of possible options. Make sense?

BTW, if you're interested in why there is a difference for a single job --> I ran a couple of profiling libraries, for example: https://pypi.org/project/pprofile/
The extra time is for the multiprocessing library to handle job allocation and also multiprocessing calls time.sleep() to make sure threads dont overlap. So sure, for a single job, it might be a second slower, but for big data, its still just a second slower, and again, no one would ever use a hyper-parameter optimization package to optimize over a set of parameters of size 1 as its pointless :)

**Comment by cgnorthcutt** [comment]
Closing but feel free to re-open if you need. Cheers!
