### ISSUE TITLE
parallelize=True not working with python 3.8.5

### ISSUE THREAD

**Issue by fcoppey** [cgnorthcutt/hypopt#22]
any workaround?

**Comment by cgnorthcutt** [comment]
For all `hypopt` issues, please provide:

1. a minimum example to replicate the error
2. the error
3. the stack trace
4. the inputs and outputs used in your minimum example
5. your python version
6. your operating system

Hypopt doesn't support Python 3.8 yet, but with this information, those of us using hypopt can take a look.

**Comment by fcoppey** [comment]
sorry I didn't take the time because I had already reverted all my venv to python 3.7 and it works perfectly. I'll wait for the compatibility with python 3.8, thanks again for the great work.
