### ISSUE TITLE
Support _ProbaScorer

### ISSUE THREAD

**Issue by anqitu** [cgnorthcutt/hypopt#3]
It is nice to allow the self-defined scoring function.

```# You provided your own scoring function.
elif type(scoring) == metrics.scorer._PredictScorer: 
       score = scoring(model, job_params["X_val"], job_params["y_val"])
```
However, is it possible to add the support for _ProbaScorer?

**Comment by cgnorthcutt** [comment]
Hi Anqi, this is a good idea. Can you submit a pull request with the change?

**Comment by cgnorthcutt** [comment]
The two lines in your pull request look good. I reviewed the diff. Please remove the 129 line changes that are just spacing or explain why those changes are needed.

**Comment by cgnorthcutt** [comment]
Thanks for the fixed pull request. Looks great. Merging to main branch.
